apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: echo-svc
spec:
  selector:
    namespace: dev
    project: infra
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
