apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: ingress-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.go-kit-boilerplate.io
      http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: echo-svc
                port:
                  name: http
          - path: /account/(.*)
            pathType: Prefix
            backend:
              service:
                name: account-svc
                port:
                  name: http
          - path: /geo/(.*)
            pathType: Prefix
            backend:
              service:
                name: geo-svc
                port:
                  name: http
          - path: /order/(.*)
            pathType: Prefix
            backend:
              service:
                name: order-svc
                port:
                  name: http
