version: "3.7"

services:
  nginx:
    image: nginx
    networks: 
      - go-kit-boilerplate
    depends_on: 
      - echo-service
      - account-service
      - order-service
      - geo-service
    ports:
      - "80:80"
      - "5040:5040"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  echo-service:
    build:
      context: ./echo
      dockerfile: Dockerfile
      args:
        APP_NAME: echo
        GOPROXY: https://goproxy.cn,direct
    networks:
      - go-kit-boilerplate

  account-service:
    build:
      context: ./account
      dockerfile: Dockerfile
      args:
        APP_NAME: account
        GOPROXY: https://goproxy.cn,direct
    networks:
      - go-kit-boilerplate

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
      args:
        APP_NAME: order
        GOPROXY: https://goproxy.cn,direct
    networks:
      - go-kit-boilerplate
      
  geo-service:
    build:
      context: ./geo
      dockerfile: Dockerfile
      args:
        APP_NAME: geo
        GOPROXY: https://goproxy.cn,direct
    networks:
      - go-kit-boilerplate

networks:
  go-kit-boilerplate:
    driver: bridge
