// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/eedkevin/go-kit-boilerplate/order"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC OrderServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.OrderServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// order

		status: grpctransport.NewServer(
			endpoints.StatusEndpoint,
			DecodeGRPCStatusRequest,
			EncodeGRPCStatusResponse,
			serverOptions...,
		),
		placeorder: grpctransport.NewServer(
			endpoints.PlaceOrderEndpoint,
			DecodeGRPCPlaceOrderRequest,
			EncodeGRPCPlaceOrderResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the OrderServer interface
type grpcServer struct {
	status     grpctransport.Handler
	placeorder grpctransport.Handler
}

// Methods for grpcServer to implement OrderServer interface

func (s *grpcServer) Status(ctx context.Context, req *pb.StatusRequest) (*pb.StatusResponse, error) {
	_, rep, err := s.status.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.StatusResponse), nil
}

func (s *grpcServer) PlaceOrder(ctx context.Context, req *pb.PlaceOrderRequest) (*pb.PlaceOrderResponse, error) {
	_, rep, err := s.placeorder.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.PlaceOrderResponse), nil
}

// Server Decode

// DecodeGRPCStatusRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC status request to a user-domain status request. Primarily useful in a server.
func DecodeGRPCStatusRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.StatusRequest)
	return req, nil
}

// DecodeGRPCPlaceOrderRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC placeorder request to a user-domain placeorder request. Primarily useful in a server.
func DecodeGRPCPlaceOrderRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.PlaceOrderRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCStatusResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain status response to a gRPC status reply. Primarily useful in a server.
func EncodeGRPCStatusResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.StatusResponse)
	return resp, nil
}

// EncodeGRPCPlaceOrderResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain placeorder response to a gRPC placeorder reply. Primarily useful in a server.
func EncodeGRPCPlaceOrderResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.PlaceOrderResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
