// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7040e72f5f
// Version Date: 2020-09-19T18:42:02Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/eedkevin/go-kit-boilerplate/account"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	StatusEndpoint            endpoint.Endpoint
	AuthTokenEndpoint         endpoint.Endpoint
	AuthTokenValidateEndpoint endpoint.Endpoint
}

// Endpoints

func (e Endpoints) Status(ctx context.Context, in *pb.StatusRequest) (*pb.StatusResponse, error) {
	response, err := e.StatusEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.StatusResponse), nil
}

func (e Endpoints) AuthToken(ctx context.Context, in *pb.AuthTokenRequest) (*pb.AuthTokenResponse, error) {
	response, err := e.AuthTokenEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.AuthTokenResponse), nil
}

func (e Endpoints) AuthTokenValidate(ctx context.Context, in *pb.AuthTokenValidateRequest) (*pb.AuthTokenValidateResponse, error) {
	response, err := e.AuthTokenValidateEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.AuthTokenValidateResponse), nil
}

// Make Endpoints

func MakeStatusEndpoint(s pb.AccountServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.StatusRequest)
		v, err := s.Status(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeAuthTokenEndpoint(s pb.AccountServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.AuthTokenRequest)
		v, err := s.AuthToken(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeAuthTokenValidateEndpoint(s pb.AccountServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.AuthTokenValidateRequest)
		v, err := s.AuthTokenValidate(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"Status":            {},
		"AuthToken":         {},
		"AuthTokenValidate": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "Status" {
			e.StatusEndpoint = middleware(e.StatusEndpoint)
		}
		if inc == "AuthToken" {
			e.AuthTokenEndpoint = middleware(e.AuthTokenEndpoint)
		}
		if inc == "AuthTokenValidate" {
			e.AuthTokenValidateEndpoint = middleware(e.AuthTokenValidateEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"Status":            {},
		"AuthToken":         {},
		"AuthTokenValidate": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "Status" {
			e.StatusEndpoint = middleware("Status", e.StatusEndpoint)
		}
		if inc == "AuthToken" {
			e.AuthTokenEndpoint = middleware("AuthToken", e.AuthTokenEndpoint)
		}
		if inc == "AuthTokenValidate" {
			e.AuthTokenValidateEndpoint = middleware("AuthTokenValidate", e.AuthTokenValidateEndpoint)
		}
	}
}
