apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: kafka-zk
  labels:
    project: kafka-zk
    app: kafka-zk
    namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: kafka-zk
      app: kafka-zk
      namespace: dev
  template:
    metadata:
      labels:
        project: kafka-zk
        app: kafka-zk
        namespace: dev
    spec:
      restartPolicy: Always
      containers:
        - name: kafka-zk
          image: johnnypark/kafka-zookeeper:2.1.0
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 9092
            - containerPort: 2181
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST
              value: $(MY_POD_IP)
            - name: NUM_PARTITIONS
              value: "1"
          # tty: true
          # livenessProbe:
          #   exec:
          #     command:
          #       - /opt/check.sh
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          # readinessProbe:
          #   exec:
          #     command:
          #       - /opt/check.sh
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
