apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: mysql
  labels:
    project: mysql
    app: mysql
    namespace: dev
spec:
  selector:
    matchLabels:
      project: mysql
      app: mysql
      namespace: dev
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: mysql
        app: mysql
        namespace: dev
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: hello123
          args:
            - --default-authentication-plugin=mysql_native_password
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
