apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: account
  labels:
    project: go-kit-boilerplate
    app: account
spec:
  selector:
    matchLabels:
      namespace: dev
      project: go-kit-boilerplate
      app: account
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        namespace: dev
        project: go-kit-boilerplate
        app: account
    spec:
      restartPolicy: Always
      containers:
        - name: account
          image: eedkevin/go-kit-boilerplate:account
          ports:
            - name: http
              containerPort: 5050
            - name: grpc
              containerPort: 5040
            - name: metrics
              containerPort: 9100
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: APP_NAME
              value: account
            - name: ENV
              value: dev
          volumeMounts:
            - mountPath: /configs/config.yaml
              name: config-volume
              subPath: config.yaml
          imagePullPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: account-cfg
