apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: mongo
  labels:
    project: mongo
    app: mongo
    namespace: dev
spec:
  selector:
    matchLabels:
      project: mongo
      app: mongo
      namespace: dev
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: mongo
        app: mongo
        namespace: dev
    spec:
      restartPolicy: Always
      containers:
        - name: mongo
          image: mongo:3.2.20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: hello123
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /data/db
              name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
