apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mongo-svc
spec:
  selector:
    project: mongo
    app: mongo
    namespace: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
